import type { DashboardTask } from '../types';

export const dashboardTasksFixture: DashboardTask[] = [
  {
    id: 'operation-ods-failed',
    title: 'ODS Codeforces 批量 upsert 失败',
    module: 'ods-import',
    status: 'failed',
    priority: 'P1',
    owner: { name: '接口操作', role: 'admin', avatar: 'API' },
    subjectLabel: '第 55 批',
    source: 'ODS',
    updatedAt: '2026-07-06T00:10:00Z',
    action: '结果',
    detail: '第 55 批 fixture 上传失败。',
  },
  {
    id: 'user-bound',
    title: '选手账号：230511214李明',
    module: 'codeforces',
    status: 'completed',
    priority: 'P3',
    owner: { name: 'Benq', role: 'player', avatar: '明' },
    subjectLabel: '230511214李明 / Benq',
    studentIdentity: '230511214李明',
    source: 'Codeforces',
    updatedAt: '2026-07-06T00:08:00Z',
    action: '查询',
    detail: 'DWS 首次通过 102 题，handle=Benq',
  },
  {
    id: 'user-unbound',
    title: '选手账号：230511213黄炳睿',
    module: 'accounts',
    status: 'pending',
    priority: 'P2',
    owner: { name: '平台账号', role: 'player', avatar: '睿' },
    subjectLabel: '230511213黄炳睿',
    studentIdentity: '230511213黄炳睿',
    source: 'Auth',
    updatedAt: '2026-07-06T00:07:00Z',
    action: '绑定',
    detail: 'auth-web 中存在账号，training-data 暂无 Codeforces 绑定。',
  },
];
